{{ if .Values.proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osproxy.fullname" . }}-config
  labels:
    component: osproxy
    {{- include "osproxy.labels" . | nindent 4 }}
    {{- with .Values.proxy.extraLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}

  {{- with .Values.proxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |-
    {{- .Values.proxy.config | nindent 4 }}
{{- end }}