{{ if .Values.osproxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osproxy.fullname" . }}
  labels:
    {{- include "osproxy.labels" . | nindent 4 }}
  {{- with .Values.osproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.osproxy.replicas }}
  selector:
    matchLabels:
      component: osproxy
      {{- include "osproxy.selectorLabels" . | nindent 6 }}

  {{- with .Values.osproxy.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    metadata:
      {{- with .Values.osproxy.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: osproxy
        {{- include "osproxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.osproxy.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osproxy.osproxy.serviceAccountName" . }}

      {{- with .Values.osproxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.osproxy.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.osproxy.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.osproxy.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.osproxy.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      {{- with .Values.osproxy.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}

          {{- with .Values.osproxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}

          {{- with .Values.osproxy.lifecycle }}
          lifecycle:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.osproxy.extraEnvironmentVars }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.osproxy.extraEnvFromVars }}
          envFrom:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.osproxy.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.osproxy.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          args:
            - serve
            - --config=/etc/osproxy/config.yaml
          {{- with .Values.osproxy.extraArgs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: osproxy-config
              mountPath: /etc/osproxy/
          {{- with .Values.osproxy.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            {{ range $key, $value := .Values.osproxy.service.ports }}
            - name: {{ $value.name }}
              containerPort: {{ $value.targetPort }}
              {{- with $value.protocol }}
              protocol: {{ . }}
              {{- end }}
            {{- end }}

            {{- with .Values.osproxy.extraPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.osproxy.resources | nindent 12 }}

        {{- with .Values.osproxy.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.osproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.osproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.osproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: osproxy-config
          configMap:
            name: {{ include "osproxy.fullname" . }}-config

      {{- with .Values.osproxy.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}