{{ if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osproxy.fullname" . }}
  labels:
    {{- include "osproxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      component: osproxy
      {{- include "osproxy.selectorLabels" . | nindent 6 }}

  {{- with .Values.proxy.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    metadata:
      {{- with .Values.proxy.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: osproxy
        {{- include "osproxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.proxy.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osproxy.proxy.serviceAccountName" . }}

      {{- with .Values.proxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.proxy.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.proxy.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.proxy.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.proxy.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      {{- with .Values.proxy.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}

          {{- with .Values.proxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}

          {{- with .Values.proxy.lifecycle }}
          lifecycle:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.proxy.extraEnvironmentVars }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.proxy.extraEnvFromVars }}
          envFrom:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.proxy.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.proxy.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          args:
            - --config
            - /etc/envoy/config.yaml
          {{- with .Values.proxy.extraArgs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: osproxy-config
              mountPath: /etc/osproxy/
          {{- with .Values.proxy.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            {{ range $key, $value := .Values.proxy.service.ports }}
            - name: {{ $value.name }}
              containerPort: {{ $value.targetPort }}
              {{- with $value.protocol }}
              protocol: {{ . }}
              {{- end }}
            {{- end }}

            {{- with .Values.proxy.extraPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}

        {{- with .Values.proxy.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: osproxy-config
          configMap:
            name: {{ include "osproxy.fullname" . }}-config

      {{- with .Values.proxy.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}