
{{- if .Values.osproxy.disruption }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "osproxy.fullname" . }}-proxy
  labels:
    {{- include "osproxy.labels" . | nindent 4 }}
  {{- with .Values.osproxy.disruption.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


spec:
  {{- with .Values.osproxy.disruption.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}

  {{- with .Values.osproxy.disruption.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}

  selector:
    matchLabels:
      component: osproxy
      {{- include "osproxy.selectorLabels" . | nindent 4 }}
---
{{- end }}
