{{ if and .Values.osproxy.enabled .Values.osproxy.extraRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "osproxy.fullname" . }}
  labels:
    {{- include "osproxy.labels" . | nindent 4 }}
  {{- with .Values.osproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- with .Values.osproxy.extraRole.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}


{{ end }}
