{{ if and .Values.osproxy.enabled (and .Values.osproxy.extraRole.create .Values.osproxy.serviceAccount.create) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "osproxy.fullname" . }}
  labels:
    {{- include "osproxy.labels" . | nindent 4 }}
  {{- with .Values.osproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

subjects:
- kind: ServiceAccount
  name: {{ include "osproxy.osproxy.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "osproxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

{{ end }}
