{{ if and .Values.proxy.enabled .Values.proxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osproxy.proxy.serviceAccountName" . }}
  labels:
    component: osproxy
    {{- include "osproxy.labels" . | nindent 4 }}
    {{- with .Values.proxy.serviceAccount.extraLabels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}

  {{- with .Values.proxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{ end }}
