{{ if and .Values.osproxy.enabled .Values.osproxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osproxy.osproxy.serviceAccountName" . }}
  labels:
    component: osproxy
    {{- include "osproxy.labels" . | nindent 4 }}
    {{- with .Values.osproxy.serviceAccount.extraLabels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}

  {{- with .Values.osproxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{ end }}
