proxy:
  address: ""
  port: "8080"
  source:
    type: pathPrefix # pathPrefix|host
    buckets:
      "path/prefix/":
        bucket: bucket-name
        object:
          removePrefix: "path/to/remove/"
    config:
      s3:
        endpoint: $OSPROXY_S3_ENDPOINT
        accessKeyId: $OSPROXY_S3_ACCESS_KEY_ID
        secretAccessKey: $OSPROXY_S3_SECRET_ACCESS_KEY
        region: $OSPROXY_S3_REGION
        secure: true
actionWorker:
  type: request
  scrapeInterval: 2s
  request:
    url: "http://example.com:8080/transfer"
