proxy:
  loglevel: "info"
  protocol: ""
  address: ""
  port: "8080"
  sources:
  - name: s3-example
    type: S3 # S3|GCS|HTTP
    s3:
      endpoint: ${ENV:OSPROXY_S3_ENDPOINT}$
      accessKeyId: ${ENV:OSPROXY_S3_ACCESS_KEY_ID}$
      secretAccessKey: ${ENV:OSPROXY_S3_SECRET_ACCESS_KEY}$
      region: eu-west-1
    # gcs:
    #   endpoint: https://storage.googleapis.com
    #   base64Credentials: exampre-gcs-credentials.json
    # http:
    #   endpoint: http://osproxy2.example.com:8080
  requestModifiers:
  - name: req-mod-example
    type: Path # Path|PathRegex|Header
    path:
      removePrefix: "path/to/remove/"
      addPrefix: "path/to/remove/"
    # header:
    #   name: "X-Real-Ip"
    #   remove: false
    #   value: "0.0.0.0"
    # pathRegex:
    #   expression: "expression"
    #   replace: "/upload/replace"
  requestRouting:
    matchType: PathPrefix # Host|PathPrefix|HeaderValue
    headerKey: X-Real-Ip
    routes:
      "path/prefix/":
        source: s3-example
        modifiers: ["req-mod-example"]
        bucket: bucket-name
  
  responseReactions:
  - name: reaction-example
    type: ResponseSustitution # PostObject|ResponseSustitution
    condition:
      key: "X-Real-Ip" # <header-key>|:status:|:host:
      value: "127.0.0.1"
    responseSustitution:
      source: gcs-example
    # postObject:
    #   endpoint: http://osproxy3.example.com:8080
