name: container-images-build

on:
  workflow_run:
    workflows: ["binaries-release"]
    types:
      - completed
  
  workflow_dispatch:
    inputs:
      release:
        description: 'Release tag where to create the binaries (as SemVer vX.X.X)'
        required: true
        default: v0.1.0

permissions:
  contents: write
  packages: write

jobs:
  container-buildx:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            current_tag="$(cat version)"
            img_ref="ghcr.io/$GITHUB_REPOSITORY:${current_tag}" 
            make docker-buildx IMG=${img_ref}
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            current_tag="${{ inputs.release }}"
            img_ref="ghcr.io/$GITHUB_REPOSITORY:${current_tag}" 
            make docker-buildx IMG=${img_ref}
          fi
